### PR TITLE
Please add "Dark Metal" skin to Mixxx :)

### PR DESCRIPTION
**Pull request by jorgerosa**
Please add "Dark Metal" skin to Mixxx. (100% SVG / 100%Resizable)
Download - http://www.mixxx.org/forums/viewtopic.php?f=8&t=6052

### CODE REVIEW

**Comment by jorgerosa** [comment]
Please add "Dark Metal" skin to Mixxx, if you agree... :)

**Comment by daschuer** [comment]
Thank you for the Pull request. It is a real fun to play with it.
I have noticed some issues: 
- The Latency meter is connected to the VU meter. 
- The right master VU meter does not refresh reliably. We had this issue with the old 1.11 Deere skin because there where a neighbour widget overlapping. 
- I am not able to maximize the skin by the windows buttons. It seems that the skin is slightly to big for my 1366 x 668 plus the Cinnamon panel and windows decoration. 
- The view menu is empty. 
  [EffectsRack],show  -> [EffectRack1],show
  [SamplersRack],show -> [Samplers],show
- It looks like I see stacked tooltips.

**Comment by daschuer** [comment]
@esbrandt: Does this suit to ship it with Mixxx?

**Comment by daschuer** [comment]
- Local Time has a stray T Prefix

**Comment by ywwg** [comment]
> @esbrandt: Does this suit to ship it with Mixxx?

currently this skin does not support 4 decks.  We should require that skins support 4 decks unless, like Shade, they are designed for very small screens.

**Comment by jorgerosa** [comment]
(...)"It is a real fun to play with it"(...) oh, yeeeah!... Just ask ywwg....
Ok guys, thanks for reporting that issues, I´ll work on it.

**Comment by jorgerosa** [comment]
Ok, I´ve updated "Dark Metal" to v.2.5, please test and report issues (help or tips to correct them will be welcome too). There are the 4 decks there, now.
Note: I think everything was updated correctly, but  since its the 1st time that I am using this github thing... please check...

**Comment by daschuer** [comment]
Once I have four decks enabled, my waveforms are jerking a lot. 
Some controls in the Mixer region are redundant. 

The four deck view is now too big on my screen to see the library. 
What is your target display size? IMO it is OK to have a Skin dedicated to big screens. 

I have never understood why it is so important to have four decks and how the use-case works. 
Maybe @ywwg can explain it.

Maybe we can catch a lot of use cases if we implement a four deck controller layout. 
Something with four deck Mixing region but only two decks visible at a time. 
And Two toggle buttons Deck A/C + Deck B/C 
This will fit nicely to your four waveform stripes. 
And will be a unique feature for this skin.

**Comment by jorgerosa** [comment]
Hi @daschuer I´ve reduced the minimun resolution to 1230x685 (lower, hides some buttons).
"Some controls in the Mixer region are redundant"... indeed.
I was thinking have only one mixer with that buttons, but then ocurred me you may have only Decks AB or only Decks CD visible at one time... Thats why they are there in both mixers... but you are right, looks ugly to me too, now that you talk about it... I´ll place them somewhere else, in a "common" area... brb.... ;)

**Comment by daschuer** [comment]
If you just toggle the view between A and C on the right and B and D on the left, it saves a lot of space and CPU time for rendering the big waveforms. The four volume sliders should be always visible. 
This is what four deck controllers so. I am not sure if this fits to @ywwg s use cases. 
We may show the hidden Deck as a small bar if required. 

What do you think about it?

**Comment by ywwg** [comment]
All four decks should be fully visible at once.  While A/B and C/D switches are common on controllers, I haven't seen anything like that for the GUI.  A mini-deck is not a good solution because the DJ has to click around the UI to swap between A/B and C/D, probably in addition to what they need to do on their controller.  We already have too much variation between how skins work, and adding switches would be yet another difference.

**Comment by jorgerosa** [comment]
@daschuer Resolution is now 1230x550 (If you had issues, other people must have to, so i´ve reduced at maximum). "The four volume sliders should be always visible"... Exactly!
@ywwg You can now switch between them (because smaller screens)... OR... have them all at once in the new "Mini Player". Works great in small screens only with the "Mini Player" visible and the "Library"... Still you will have the 4 decks there. Have Fun! :)

**Comment by ywwg** [comment]
can you post an updated screenshot showing these mini players?

**Comment by jorgerosa** [comment]
@ywwg sure.
Here: https://30546d01-a-62cb3a1a-s-sites.googlegroups.com/site/jorgerosaportfolio/home/mixxx_dark_metal_miniplayer.jpg

**Comment by ywwg** [comment]
Sorry, these mini players aren't quite what I meant by having all four players visible.  Please see Deere and Latenight for examples of what I mean.  The four decks need to be fully interactive with all of the controls required to DJ with them.  Yes this requires a larger screen, but LateNight and Deere are usable at 1366x768, which is our most popular screen resolution.

Currently we are working on a set of guidelines for our officially-bundled skins.  Skin maintenance is extremely difficult and time consuming and require constant maintenance to keep them up to date with changes in the codebase.  Skins are never "done."  Latenight, Deere, and Shade took over a year to update from their old versions and had to be redone from scratch. Given the large amount of work required, we are very hesitant to adopt a new skin into the official set.  As an alternative we are working on options for community-supported skins so they are easier to find and download than from the forums.

**Comment by jorgerosa** [comment]
Sure, no worries. I just developed it to fit my own taste, and by now I really know what you mean by LOT of work in the skins.

**Comment by jorgerosa** [comment]
- Finally the skin is almost "finished" to achieve my initial idea of it:
  An Hi-fi, with leds display, 100% SVG, Resizeable. To be playing nicelly, in my house and in office, in a big screen ;) (As my "avatar", the "ascr" text in the skin is the name of my little daugther)
- Can now be reduced as much as 1230x550 (still have the 4 decks, but only 2 visible at a time). The minimun for all the 4 decks being visible at the same time is 1230x700 (without overlaping).
- The colors have changed (The reds are beautiful, but were too agressive, even I counldnt support them anymore). So the most common "oldies" hifi leds display colors were used instead.
- The minimum for the skin size could be even more smaller, but... Since I intend to make it with a "real hifi feeling", I rejected all accordion effects in the graphics (racks). I want to achive a "solid" and "real" aspect in any resolution.
- The files were commented and cleaned, everything, specially the files, in the most obvious and in the "right place". Good for anyone that wants to improve it, without losing much time to search for stuff. All the used tools and the "zip" file for download, are here too:
  http://www.mixxx.org/forums/viewtopic.php?f=8&t=6052
  (Only the tree icons werent customized, they still are in yellow ("hardcoded"), but Pegasus (from IRC channel) is reporting it as a mixxx "bug". And as soon I can change them... I´ll do it, of course)
  I´ll keep an eye on others skins too, to keep this one as updated as possible.

**Comment by daschuer** [comment]
I had just time to look at it and it is really nice. It feels pretty mature, unfortunately a bit big for my HD-Ready screen, but that's OK, we don't need to make every skin fit on all screens. 

Why did you close this PR? Would you mind issue a new one against git@github.com:mixxxdj/mixxx.git? 
This developer_skins repository is only for experimental skins.

**Comment by daschuer** [comment]
Some comments: 
- What mean mixxxdm? 
- The view menu is out of works.
- Did you check the color sheme feature of the Shade skin? Is it useful to colour you skin as well? 
  If not, I am willing to improve it for your needs.
- It would be really nice, If we can load the font from the skin directory. Do you have an idea what is required for this?

**Comment by jorgerosa** [comment]
1) What mean mixxxdm? Mixxx + Dark Metal == MixxxDM.
Note 1: Dark Metal refers to this skin, because the dark colors that I intended to use, since the beginning. Nothing to do to genre of music. Was not the best choice, but its already known by that name, so maybe I´ll keep it. Note 2: The text "ASCR" there, is the name of my little daughter.

2) The view menu is out of works.
Sorry, I dont understant that. (If you refer to the skin´s tree view (library), I´ve customized everything I can. Except that yellow icons, because they are "hardcoded")

3) Did you check the color sheme feature of the Shade skin?
Nope, but I´ll do right away! [EDIT: Features added. Done!]

4) Load the font from the skin directory...
Would be great indeed, I´ve no idea atm, but I´ll digg on that.
In the end, if we could achieve something like this in the skin.xml: <font name="hello">myfonts/helloall.ttf</font> would be nice.

5) Why did you close this PR
I´m from "oldschool" and I am used to sourceforge (almost all my opensource projects are there). ywwg helped me to create a branch here, etc... But every day was a fight with that git console in my PC... I was wasting my time with that instead of developing stuff, thats why I´ve quitted. I removed the skin from there because if people had access to it there, they will be downloading only deprecated stuff, instead of download from the forum, where I´ve been constantly (almost daily) updating it. BUT, of course, as this skin is enought mature, if needed, then I´ll focus on the GITHUB and learn all about it, and upload it. No problem!

Thanks for your comments Daniel, and... Very glad that you like it! :)

**Pull request closed without merging**
